name: json_api
version: 4.3.0
description: "Framework-agnostic implementations of JSON:API Client (Flutter, Web and VM) and Server (VM). Supports JSON:API v1.0 (http://jsonapi.org)"
homepage: "https://github.com/f3ath/json-api-dart"

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0

dev_dependencies:
  args: ^1.6.0
  json_matcher: ^0.2.4
  pedantic: ^1.11.0
  shelf: ^1.0.0
  stream_channel: ^2.1.0
  test: ^1.16.5
  test_coverage: ^0.5.0
  uuid: ^3.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
